using System;
using System.Collections.Generic;

namespace DrawAndGuess.Utils
{
    public static class SecretWords
    {
        private static Random _random = new Random();
        public static readonly string[] Words =
        {
            "ant",
            "arm",
            "axe",
            "bad",
            "bag",
            "bar",
            "bat",
            "bed",
            "bee",
            "bow",
            "box",
            "boy",
            "bus",
            "can",
            "cap",
            "cat",
            "dock",
            "doll",
            "dome",
            "door",
            "dots",
            "drip",
            "drum",
            "duck",
            "duel",
            "east",
            "echo",
            "exam",
            "face",
            "adult",
            "alarm",
            "alien",
            "alley",
            "angel",
            "angry",
            "anime",
            "anvil",
            "Apple",
            "armor",
            "arrow",
            "attic",
            "bacon",
            "bagel",
            "Bambi",
            "banjo",
            "beach",
            "belly",
            "below",
            "bench",
            "Bible",
            "bingo",
            "birch",
            "black",
            "blimp",
            "Africa",
            "airbag",
            "almond",
            "alpaca",
            "anchor",
            "Anubis",
            "archer",
            "armpit",
            "baboon",
            "badger",
            "bakery",
            "ballet",
            "bamboo",
            "banana",
            "banker",
            "barber",
            "barrel",
            "basket",
            "Batman",
            "battle",
            "beanie",
            "beaver",
            "beetle",
            "Tetris",
            "thirst",
            "throat",
            "throne",
            "ticket",
            "tickle",
            "tissue",
            "toilet",
            "tomato",
            "tongue",
            "toucan",
            "tripod",
            "trophy",
            "tunnel",
            "manhole",
            "mansion",
            "maracas",
            "massage",
            "meerkat",
            "Mercury",
            "mermaid",
            "message",
            "milkman",
            "minivan",
            "missile",
            "monster",
            "morning",
            "Mr Bean",
            "mustard",
            "narwhal",
            "Neptune",
            "network",
            "beanstalk",
            "bear trap",
            "bed sheet",
            "Beethoven",
            "billiards",
            "bird bath",
            "blindfold",
            "blueberry",
            "bodyguard",
            "Bomberman",
            "bookshelf",
            "boomerang",
            "brainwash",
            "breakfast",
            "broadcast",
            "Bruce Lee",
            "bulldozer",
            "butterfly",
            "Capricorn",
            "cardboard",
            "carnivore",
            "carpenter",
            "Cat Woman",
            "cathedral",
            "celebrate",
            "celebrity",
            "centipede",
            "chameleon",
            "champagne",
            "Chewbacca",
            "chihuahua",
            "Chinatown",
            "chocolate",
            "Christmas",
            "cigarette",
            "classroom",
            "clickbait",
            "clownfish",
            "cockroach",
            "Colosseum",
            "commander",
            "high heels",
            "high score",
            "hitchhiker",
            "Home Alone",
            "hovercraft",
            "Iron Giant",
            "jackhammer",
            "James Bond",
            "journalist",
            "Katy Perry",
            "laboratory",
            "lawn mower",
            "leprechaun",
            "lighthouse",
            "lightsaber",
            "litter box",
            "London Eye",
            "lumberjack",
            "Madagascar",
            "magic wand",
            "mayonnaise",
            "microphone",
            "microscope",
            "Mont Blanc",
            "Morse code",
            "motorcycle",
            "nutcracker",
            "overweight",
            "pharmacist",
        };

        public static string[] GetTreeRandomWords()
        {
            var randomWords = new List<string>();
            do
            {
                int index = _random.Next(Words.Length);
                if (!randomWords.Contains(Words[index]))
                {
                    randomWords.Add(Words[index]);
                }
            } while (randomWords.Count < 3);

            return randomWords.ToArray();
        }
    }
}
